name = "hex-gfq-field"
defaultTargets = ["HexGFqField"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexGFqRing"
git = "https://github.com/leanprover/hex-gfq-ring.git"
rev = "5d6988368887a11b0a370c3140a7157dd77eebb7"

[[require]]
name = "HexBerlekamp"
git = "https://github.com/leanprover/hex-berlekamp.git"
rev = "c5126ce15c2d77ce2832eb1013840b2dacd91c12"

[[lean_lib]]
name = "HexGFqField"
